### ISSUE TITLE
请问还需要添加其他的包吗？

### ISSUE THREAD

**Issue by Tim-Xue** [Zoctan/Translator#2]
新手小白，想实现屏幕划词，看到你的程序里好像有实现这个功能，但是按你的源代码跑不出来。

**Comment by Zoctan** [comment]
我写了暂未实现这四个字啦……我下面有提供思路，你可以参考一下，工具包里有个被我注释掉掉Tess4jUtils，如果你把图片都截取出来了，你就可以调用它来得出你的单词了。

**Comment by Tim-Xue** [comment]
也就是说你目前还没实现屏幕划词翻译这个功能是嘛？（其实我连你程序运行都不行，好像少了阿里的包，你能指点我一下嘛？）

**Comment by Zoctan** [comment]
嗯，目前还没时间做，只有简单思路。
先把工程转成maven的，idea会让你选择是否自动导入这些包，我试过一遍没有问题。
