### ISSUE TITLE
Windows 10 , Eclipse运行, 查词正常, OCR取词没反应

### ISSUE THREAD

**Issue by a442509097** [Zoctan/Translator#3]
已安装好Tesseract-OCR, 环境变量, tesseract -v显示正常.
另外想问下作者, Java没办法像Windows原生程序那样直接获取系统内部的取词字符串吗, 网上好像没找到相关的库.

**Comment by Zoctan** [comment]
@a442509097 “直接获取系统内部的取词字符串”这句话是啥意思，有例子图片吗，很久没用Windows了

**Comment by a442509097** [comment]
就是Windows原生开发的软件都支持这个功能, 如海词, 金山词霸的划词翻译

**Comment by Zoctan** [comment]
@a442509097 如果你是指把词汇选中然后翻译，可以考虑用鼠标事件+粘贴板来做，这里没有实现
